#cloud-config
ssh_authorized_keys:
  - ssh-rsa ssh-rsa PUBLICKEY

package_update: true

packages:
 - curl
 - jq

write_files:
  - content: |-
      my dummy content

    owner: ubuntu:ubuntu
    path: /home/ubuntu/file.txt
    permissions: '0644'

bootcmd:
  - echo $(whoami) > /root/boot.txt

runcmd:
  - cp /root/boot.txt /home/ubuntu/boot_moved.txt
  - chown ubuntu:ubuntu /home/ubuntu/boot_moved.txt
  - curl -s http://dummy.restapiexample.com/api/v1/employees | jq '.data[] | select(.id == "1") | .employee_name' > /home/ubuntu/api_output.txt
